version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - jc

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch
    ports:
      - 5044:5044
    networks:
      - jc

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - jc

networks:
  jc:
    external:
      name: jc