version: '3'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.1.1-python3.8
  environment:
    &airflow-common-env
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://airflow:airflow@mysql:3306/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
  volumes:
    - /d/Workspace/Devops/volume/airflow/dags:/opt/airflow/dags
    - /d/Workspace/Devops/volume/airflow/logs:/opt/airflow/logs
    - /d/Workspace/Devops/volume/airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    mysql:
      condition: service_healthy
  networks:
    - jc

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: airflow
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
      MYSQL_DATABASE: airflow
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 2s
      retries: 120

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
      /bin/bash -c "
        airflow db init
        airflow db upgrade
        airflow users create -r Admin -u admin -e airflow@airflow.com -f admin -l user -p airflow
      "
    environment:
      <<: *airflow-common-env

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    environment:
      <<: *airflow-common-env
    restart: always

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    environment:
      <<: *airflow-common-env

# Names our volume
volumes:
  mysql:
    external:
      name: mysql-airflow

networks:
  jc:
    external:
      name: jc