version: "3"
services:
  mysql-master:
    container_name: mysql-master
    image: mysql:8.0.30
    command: "mysqld \  
    --server-id=1 \
    --default-authentication-plugin=mysql_native_password \
    --log-bin='mysql-bin-1.log' \
    --relay_log_info_repository=TABLE \
    --master-info-repository=TABLE \
    --gtid-mode=ON \
    --log-slave-updates=ON \
    --enforce-gtid-consistency"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - jc

  mysql-slave-1:
    container_name: mysql-slave-1
    image: mysql:8.0.30
    command: "mysqld \
      --server-id=2 \
      --default-authentication-plugin=mysql_native_password \
      --enforce-gtid-consistency=ON \
      --log-slave-updates=ON \
      --read_only=TRUE \
      --skip-log-bin \
      --skip-log-slave-updates \
      --gtid-mode=ON"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    networks:
      - jc

  mysql-slave-2:
    container_name: mysql-slave-2
    image: mysql:8.0.30
    command: "mysqld \
      --server-id=3 \
      --default-authentication-plugin=mysql_native_password \
      --enforce-gtid-consistency=ON \
      --log-slave-updates=ON \
      --read_only=TRUE \
      --skip-log-bin \
      --skip-log-slave-updates \
      --gtid-mode=ON"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3308:3306
    networks:
      - jc

networks:
  jc:
    name: jc
    external: true