version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - storm

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    networks:
      - storm

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    networks:
      - storm

  ui:
    image: storm
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    restart: always
    ports:
      - 8080:8080
    networks:
      - storm

networks:
  storm:
    external:
      name: storm