version: "3"
services:
  activemq-artemis:
    container_name: activemq-artemis
    image: vromero/activemq-artemis:latest
    environment:
      ARTEMIS_USERNAME: 'activemq-artemis'
      ARTEMIS_PASSWORD: 'password'
    ports:
      - 8161:8161
      - 61616:61616
    networks:
      - jc

networks:
  jc:
    external:
      name: jc