version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - lsr
      
networks:
  lsr:
    external:
      name: lsr