version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - lsr

  kibana:
    container_name: kibana
    image: kibana:7.4.1
    ports:
      - 5601:5601
    networks:
      - lsr
    depends_on:
      - elasticsearch
  
  logstash:
    container_name: logstash
    image: logstash:7.4.1
    ports:
      - 25826:25826
    command: logstash -f logstash.config
    networks:
      - lsr
    depends_on:
      - elasticsearch