version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - jc
    volumes:
      - mongo:/var/lib/mongodb

networks:
  jc:
    external:
      name: jc

volumes:
  mongo:
    external:
      name: mongo