version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - lsr
    volumes:
      - mongo:/var/lib/mongodb

networks:
  lsr:
    external:
      name: lsr

volumes:
  mongo:
    external:
      name: mongo