version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - lsr
    volumes:
      - mysql:/var/lib/mysql

networks:
  lsr:
    external:
      name: lsr

volumes:
  mysql:
    external:
      name: mysql-beer