version: "3"
services:
  oracle:
    container_name: oracle
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - jc
      
  weblogic:
    image: store/oracle/weblogic:12.2.1.4-191221
    container_name: weblogic
    ports:
      - 7001:7001
      - 9002:9002
    networks:
      - jc
    volumes:
      - /c/docker-volume/jda/oracle:/u01/oracle/properties

networks:
  jc:
    external:
      name: jc